/**
 * Geo Controller
 * Returns the visitor's country, currency, and country name.
 * Uses the Cloudflare CF-IPCountry header extracted by locationMiddleware (req.location),
 * with no dependency on any third-party HTTP service.
 */

// Comprehensive country → { currency, name } map
const COUNTRY_DATA = {
  AF: { currency: 'AFN', name: 'Afghanistan' },
  AL: { currency: 'ALL', name: 'Albania' },
  DZ: { currency: 'DZD', name: 'Algeria' },
  AD: { currency: 'EUR', name: 'Andorra' },
  AO: { currency: 'AOA', name: 'Angola' },
  AG: { currency: 'XCD', name: 'Antigua and Barbuda' },
  AR: { currency: 'ARS', name: 'Argentina' },
  AM: { currency: 'AMD', name: 'Armenia' },
  AU: { currency: 'AUD', name: 'Australia' },
  AT: { currency: 'EUR', name: 'Austria' },
  AZ: { currency: 'AZN', name: 'Azerbaijan' },
  BS: { currency: 'BSD', name: 'Bahamas' },
  BH: { currency: 'BHD', name: 'Bahrain' },
  BD: { currency: 'BDT', name: 'Bangladesh' },
  BB: { currency: 'BBD', name: 'Barbados' },
  BY: { currency: 'BYN', name: 'Belarus' },
  BE: { currency: 'EUR', name: 'Belgium' },
  BZ: { currency: 'BZD', name: 'Belize' },
  BJ: { currency: 'XOF', name: 'Benin' },
  BT: { currency: 'BTN', name: 'Bhutan' },
  BO: { currency: 'BOB', name: 'Bolivia' },
  BA: { currency: 'BAM', name: 'Bosnia and Herzegovina' },
  BW: { currency: 'BWP', name: 'Botswana' },
  BR: { currency: 'BRL', name: 'Brazil' },
  BN: { currency: 'BND', name: 'Brunei' },
  BG: { currency: 'BGN', name: 'Bulgaria' },
  BF: { currency: 'XOF', name: 'Burkina Faso' },
  BI: { currency: 'BIF', name: 'Burundi' },
  CV: { currency: 'CVE', name: 'Cape Verde' },
  KH: { currency: 'KHR', name: 'Cambodia' },
  CM: { currency: 'XAF', name: 'Cameroon' },
  CA: { currency: 'CAD', name: 'Canada' },
  CF: { currency: 'XAF', name: 'Central African Republic' },
  TD: { currency: 'XAF', name: 'Chad' },
  CL: { currency: 'CLP', name: 'Chile' },
  CN: { currency: 'CNY', name: 'China' },
  CO: { currency: 'COP', name: 'Colombia' },
  KM: { currency: 'KMF', name: 'Comoros' },
  CG: { currency: 'XAF', name: 'Congo' },
  CD: { currency: 'CDF', name: 'DR Congo' },
  CR: { currency: 'CRC', name: 'Costa Rica' },
  HR: { currency: 'EUR', name: 'Croatia' },
  CU: { currency: 'CUP', name: 'Cuba' },
  CY: { currency: 'EUR', name: 'Cyprus' },
  CZ: { currency: 'CZK', name: 'Czech Republic' },
  DK: { currency: 'DKK', name: 'Denmark' },
  DJ: { currency: 'DJF', name: 'Djibouti' },
  DM: { currency: 'XCD', name: 'Dominica' },
  DO: { currency: 'DOP', name: 'Dominican Republic' },
  EC: { currency: 'USD', name: 'Ecuador' },
  EG: { currency: 'EGP', name: 'Egypt' },
  SV: { currency: 'USD', name: 'El Salvador' },
  GQ: { currency: 'XAF', name: 'Equatorial Guinea' },
  ER: { currency: 'ERN', name: 'Eritrea' },
  EE: { currency: 'EUR', name: 'Estonia' },
  SZ: { currency: 'SZL', name: 'Eswatini' },
  ET: { currency: 'ETB', name: 'Ethiopia' },
  FJ: { currency: 'FJD', name: 'Fiji' },
  FI: { currency: 'EUR', name: 'Finland' },
  FR: { currency: 'EUR', name: 'France' },
  GA: { currency: 'XAF', name: 'Gabon' },
  GM: { currency: 'GMD', name: 'Gambia' },
  GE: { currency: 'GEL', name: 'Georgia' },
  DE: { currency: 'EUR', name: 'Germany' },
  GH: { currency: 'GHS', name: 'Ghana' },
  GR: { currency: 'EUR', name: 'Greece' },
  GD: { currency: 'XCD', name: 'Grenada' },
  GT: { currency: 'GTQ', name: 'Guatemala' },
  GN: { currency: 'GNF', name: 'Guinea' },
  GW: { currency: 'XOF', name: 'Guinea-Bissau' },
  GY: { currency: 'GYD', name: 'Guyana' },
  HT: { currency: 'HTG', name: 'Haiti' },
  HN: { currency: 'HNL', name: 'Honduras' },
  HK: { currency: 'HKD', name: 'Hong Kong' },
  HU: { currency: 'HUF', name: 'Hungary' },
  IS: { currency: 'ISK', name: 'Iceland' },
  IN: { currency: 'INR', name: 'India' },
  ID: { currency: 'IDR', name: 'Indonesia' },
  IR: { currency: 'IRR', name: 'Iran' },
  IQ: { currency: 'IQD', name: 'Iraq' },
  IE: { currency: 'EUR', name: 'Ireland' },
  IL: { currency: 'ILS', name: 'Israel' },
  IT: { currency: 'EUR', name: 'Italy' },
  JM: { currency: 'JMD', name: 'Jamaica' },
  JP: { currency: 'JPY', name: 'Japan' },
  JO: { currency: 'JOD', name: 'Jordan' },
  KZ: { currency: 'KZT', name: 'Kazakhstan' },
  KE: { currency: 'KES', name: 'Kenya' },
  KI: { currency: 'AUD', name: 'Kiribati' },
  KW: { currency: 'KWD', name: 'Kuwait' },
  KG: { currency: 'KGS', name: 'Kyrgyzstan' },
  LA: { currency: 'LAK', name: 'Laos' },
  LV: { currency: 'EUR', name: 'Latvia' },
  LB: { currency: 'LBP', name: 'Lebanon' },
  LS: { currency: 'LSL', name: 'Lesotho' },
  LR: { currency: 'LRD', name: 'Liberia' },
  LY: { currency: 'LYD', name: 'Libya' },
  LI: { currency: 'CHF', name: 'Liechtenstein' },
  LT: { currency: 'EUR', name: 'Lithuania' },
  LU: { currency: 'EUR', name: 'Luxembourg' },
  MO: { currency: 'MOP', name: 'Macau' },
  MG: { currency: 'MGA', name: 'Madagascar' },
  MW: { currency: 'MWK', name: 'Malawi' },
  MY: { currency: 'MYR', name: 'Malaysia' },
  MV: { currency: 'MVR', name: 'Maldives' },
  ML: { currency: 'XOF', name: 'Mali' },
  MT: { currency: 'EUR', name: 'Malta' },
  MH: { currency: 'USD', name: 'Marshall Islands' },
  MR: { currency: 'MRU', name: 'Mauritania' },
  MU: { currency: 'MUR', name: 'Mauritius' },
  MX: { currency: 'MXN', name: 'Mexico' },
  FM: { currency: 'USD', name: 'Micronesia' },
  MD: { currency: 'MDL', name: 'Moldova' },
  MC: { currency: 'EUR', name: 'Monaco' },
  MN: { currency: 'MNT', name: 'Mongolia' },
  ME: { currency: 'EUR', name: 'Montenegro' },
  MA: { currency: 'MAD', name: 'Morocco' },
  MZ: { currency: 'MZN', name: 'Mozambique' },
  MM: { currency: 'MMK', name: 'Myanmar' },
  NA: { currency: 'NAD', name: 'Namibia' },
  NR: { currency: 'AUD', name: 'Nauru' },
  NP: { currency: 'NPR', name: 'Nepal' },
  NL: { currency: 'EUR', name: 'Netherlands' },
  NZ: { currency: 'NZD', name: 'New Zealand' },
  NI: { currency: 'NIO', name: 'Nicaragua' },
  NE: { currency: 'XOF', name: 'Niger' },
  NG: { currency: 'NGN', name: 'Nigeria' },
  MK: { currency: 'MKD', name: 'North Macedonia' },
  NO: { currency: 'NOK', name: 'Norway' },
  OM: { currency: 'OMR', name: 'Oman' },
  PK: { currency: 'PKR', name: 'Pakistan' },
  PW: { currency: 'USD', name: 'Palau' },
  PA: { currency: 'PAB', name: 'Panama' },
  PG: { currency: 'PGK', name: 'Papua New Guinea' },
  PY: { currency: 'PYG', name: 'Paraguay' },
  PE: { currency: 'PEN', name: 'Peru' },
  PH: { currency: 'PHP', name: 'Philippines' },
  PL: { currency: 'PLN', name: 'Poland' },
  PT: { currency: 'EUR', name: 'Portugal' },
  QA: { currency: 'QAR', name: 'Qatar' },
  RO: { currency: 'RON', name: 'Romania' },
  RU: { currency: 'RUB', name: 'Russia' },
  RW: { currency: 'RWF', name: 'Rwanda' },
  KN: { currency: 'XCD', name: 'Saint Kitts and Nevis' },
  LC: { currency: 'XCD', name: 'Saint Lucia' },
  VC: { currency: 'XCD', name: 'Saint Vincent and the Grenadines' },
  WS: { currency: 'WST', name: 'Samoa' },
  SM: { currency: 'EUR', name: 'San Marino' },
  ST: { currency: 'STN', name: 'Sao Tome and Principe' },
  SA: { currency: 'SAR', name: 'Saudi Arabia' },
  SN: { currency: 'XOF', name: 'Senegal' },
  RS: { currency: 'RSD', name: 'Serbia' },
  SC: { currency: 'SCR', name: 'Seychelles' },
  SL: { currency: 'SLE', name: 'Sierra Leone' },
  SG: { currency: 'SGD', name: 'Singapore' },
  SK: { currency: 'EUR', name: 'Slovakia' },
  SI: { currency: 'EUR', name: 'Slovenia' },
  SB: { currency: 'SBD', name: 'Solomon Islands' },
  SO: { currency: 'SOS', name: 'Somalia' },
  ZA: { currency: 'ZAR', name: 'South Africa' },
  SS: { currency: 'SSP', name: 'South Sudan' },
  ES: { currency: 'EUR', name: 'Spain' },
  LK: { currency: 'LKR', name: 'Sri Lanka' },
  SD: { currency: 'SDG', name: 'Sudan' },
  SR: { currency: 'SRD', name: 'Suriname' },
  SE: { currency: 'SEK', name: 'Sweden' },
  CH: { currency: 'CHF', name: 'Switzerland' },
  SY: { currency: 'SYP', name: 'Syria' },
  TW: { currency: 'TWD', name: 'Taiwan' },
  TJ: { currency: 'TJS', name: 'Tajikistan' },
  TZ: { currency: 'TZS', name: 'Tanzania' },
  TH: { currency: 'THB', name: 'Thailand' },
  TL: { currency: 'USD', name: 'Timor-Leste' },
  TG: { currency: 'XOF', name: 'Togo' },
  TO: { currency: 'TOP', name: 'Tonga' },
  TT: { currency: 'TTD', name: 'Trinidad and Tobago' },
  TN: { currency: 'TND', name: 'Tunisia' },
  TR: { currency: 'TRY', name: 'Turkey' },
  TM: { currency: 'TMT', name: 'Turkmenistan' },
  TV: { currency: 'AUD', name: 'Tuvalu' },
  UG: { currency: 'UGX', name: 'Uganda' },
  UA: { currency: 'UAH', name: 'Ukraine' },
  AE: { currency: 'AED', name: 'United Arab Emirates' },
  GB: { currency: 'GBP', name: 'United Kingdom' },
  US: { currency: 'USD', name: 'United States' },
  UY: { currency: 'UYU', name: 'Uruguay' },
  UZ: { currency: 'UZS', name: 'Uzbekistan' },
  VU: { currency: 'VUV', name: 'Vanuatu' },
  VE: { currency: 'VES', name: 'Venezuela' },
  VN: { currency: 'VND', name: 'Vietnam' },
  YE: { currency: 'YER', name: 'Yemen' },
  ZM: { currency: 'ZMW', name: 'Zambia' },
  ZW: { currency: 'ZWG', name: 'Zimbabwe' },
};

const DEFAULT = { countryCode: 'IN', currency: 'INR', countryName: 'India' };

/**
 * @desc  Return visitor's detected country, currency, and country name
 * @route GET /api/v1/geo
 * @access Public
 */
exports.getGeo = (req, res) => {
  // req.location is set by extractLocation middleware from CF-IPCountry header
  const countryCode = req.location || DEFAULT.countryCode;
  const info = COUNTRY_DATA[countryCode];

  res.json({
    success: true,
    countryCode,
    currency: info ? info.currency : DEFAULT.currency,
    countryName: info ? info.name : DEFAULT.countryName,
  });
};
